target 'HideAndUnhideTableViewController' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
   # pod 'LFSideViewController', '~> 2.0.0'
    pod 'GoogleMaps'
    pod 'GooglePlaces'
   # pod 'FormTextField'
    #pod 'SideMenuController'
  pod 'GooglePlacePicker'

end
